### ISSUE TITLE
Mismatch Dimension when Calculating Q

### ISSUE THREAD

**Issue by hungdche** [rohiitb/msckf_vio_python#1]
Thank you for a great open-source project!

When I ran the code, an error pops up in [this line](https://github.com/rohiitb/msckf_vio_python/blob/15307ea5f3fa2e15a3219d54f41e306fea83ad39/msckf.py#L351). 

It seems that `Phi` and `G` are both 21x21 matrix, whereas `self.state_server.continuous_noise_cov` is 12x12. 

Any help is much appreciated!

**Comment by AKkellan** [comment]
@hungdche hello, I also meet this problem, how didi u deal with it?Thanks!
